global:
  insecureFlag: true
  secretName: vsphere-creds
  secretNamespace: kube-system
vcenter:
  vcenter.test.openshift.com:
    server: vcenter.test.openshift.com
    port: 443
    insecureFlag: true
    datacenters:
      - cidatacenter
  vcenter2.test.openshift.com:
    server: vcenter2.test.openshift.com
    port: 443
    insecureFlag: true
    datacenters:
      - IBMCloud
labels:
  zone: openshift-zone
  region: openshift-region
